seed: 42

data_path: data/train
dataset: movie

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
field_separator: "\t"

load_col:
  inter: [user_id, item_id,timestamp]

# ADMM-based SLIM (default hyperparameters)
model: ADMMSLIM

# ===== ADMMSLIM defaults =====
lambda1: 3.0
lambda2: 200.0
alpha: 0.5
rho: 5000.0
k: 50
positive_only: False
center_columns: True
# ==============================

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: Recall@10