seed: 42

data_path: data/train
dataset: movie

USER_ID_FIELD: user
ITEM_ID_FIELD: item
field_separator: "\t"

load_col:
  inter: [user, item]

model: EASE
reg_weight: 250.0

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: Recall@10
