seed: 42

data_path: data/train
dataset: movie

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
field_separator: "\t"

load_col:
  inter: [user_id, item_id, timestamp, rating]

model: ItemKNN

k: 100
shrink: 0.0

epochs: 300
eval_step: 1
stopping_step: 10

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: Recall@10
