seed: 42

data_path: data/train
dataset: movie

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
field_separator: "\t"

load_col:
  inter: [user_id, item_id, timestamp]

# 모델명 & 파라미터
model: MultiVAE
latent_dimension:128 # 64/128/256 비교
mlp_hidden_size: [600]
dropout_prob: 0.5
anneal_cap: 0.2
total_anneal_steps: 200000

train_batch_size: 2048
learner: adam
learning_rate: 0.001
weight_decay: 0.0

train_neg_sample_args: {}

show_progress: False

eval_step: 1
stopping_step: 10

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ["Recall", "NDCG"]
topk: [10]
valid_metric: Recall@10
valid_metric_bigger: True

eval_batch_size: 4096