seed: 42

data_path: data/train
dataset: movie

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
field_separator: "\t"

load_col:
  inter: [user_id, item_id, timestamp, rating]

model: NeuMF

mf_embedding_size: 64
mlp_embedding_size: 64
mlp_hidden_size: [128, 64]
dropout_prob: 0.1

mf_train: True
mlp_train: True

use_pretrain: False
mf_pretrain_path: None
mlp_pretrain_path: None

epochs: 300
eval_step: 1
stopping_step: 10

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: Recall@10
