# 1. 기본 설정
gpu_id: '0'
worker: 4
seed: 42
state: INFO
reproducibility: true

# 2. 데이터 설정
data_path: data/train
dataset: movie
field_separator: "\t"

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, genre]

#ITEM_LIST_LENGTH_FIELD: item_length

# 3. 모델 구조
model: S3Rec
train_stage: finetune

# 학습에 사용할 아이템 속성 지정
selected_features: ['genre']

# 모델 하이퍼파라미터
hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
MAX_ITEM_LIST_LENGTH: 50

hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02

pre_model_path: saved/S3Rec-movie-10.pth

loss_type: CE
train_neg_sample_args: ~

epochs: 200
eval_step: 1
stopping_step: 10

eval_args:
  group_by: user
  order: TO
  split:
    LS: valid_and_test
  mode: full

metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: Recall@10