# 1. 기본 설정
gpu_id: '0'
worker: 4
seed: 42
state: INFO
reproducibility: true

# 2. 데이터 설정
data_path: data/train
dataset: movie
field_separator: "\t"

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, genre]

# 3. 모델 구조
model: S3Rec
train_stage: pretrain

# 학습에 사용할 아이템 속성 지정
selected_features: ['genre']

# 아키텍처 파라미터
hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
hidden_act: gelu
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
initializer_range: 0.02
MAX_ITEM_LIST_LENGTH: 50
layer_norm_eps: 1e-12

# Negative Sampling 끄기
train_neg_sample_args: ~

# S3Rec 전용 파라미터
mask_ratio: 0.2
mip_weight: 1.0
map_weight: 1.0
aap_weight: 0.2
sp_weight: 0.5

# 4. 학습 설정
epochs: 100
train_batch_size: 16384 # 8192, 2048
learner: adam
learning_rate: 0.001
save_step: 10
weight_decay: 0.0
eval_step: 0