seed: 42
reproducibility: true

data_path: data/train
dataset: movie

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

field_separator: "\t"

load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id, genre]

LIST_SUFFIX: _list
ITEM_LIST_LENGTH_FIELD: item_length
MAX_ITEM_LIST_LENGTH: 50

model: S3Rec

hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
train_neg_sample_args: ~
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02

train_stage: pretrain
mask_ratio: 0.2

item_attribute: genre

aap_weight: 1.0
mip_weight: 0.2
map_weight: 1.0
sp_weight: 0.5

pretrain_epochs: 100
save_step: 10
