# 1. 환경 설정
gpu_id: '0'
worker: 4
seed: 42
state: INFO             # 로그 레벨 설정
reproducibility: True  # 재현성 설정

# 2. 데이터 설정
data_path: data/train
dataset: movie

# 컬럼 매핑
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
field_separator: "\t"

# 데이터 로드 설정
load_col:
  inter: [user_id, item_id, timestamp]

LIST_SUFFIX: _list
ITEM_LIST_LENGTH_FIELD: item_length
MAX_ITEM_LIST_LENGTH: 50

# 3. 모델 설정
model: SASRec

hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2

hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5

hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02

loss_type: CE
train_neg_sample_args: ~

# 4. 학습 설정
epochs: 200
train_batch_size: 16384 # 8192
learner: Adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
weight_decay: 0.0
clip_grad_norm: {'max_norm': 5, 'norm_type': 2}

# 5. 평가 설정
eval_args:
  group_by: user
  order: TO
  split:
    LS: valid_and_test
  mode: full


metrics: ['Recall', 'NDCG']
topk: [5, 10]
valid_metric: Recall@10
eval_batch_size: 40960